export const GET_ERRORS='GET_ERRORS';
export const SET_CURRENT_USER ='SET_CURRENT_USER';
export const CLEAR_CURRENT_PROFILE='CLEAR_CURRENT_PROFILE';
export const REORDER_LIST='REORDER_LIST';
export const REORDER_CARD='REORDER_CARD';
export const RETRIEVE_ALL_BOARDS='RETRIEVE_ALL_BOARDS';
export const SET_CURRENT_CARDS='SET_CURRENT_CARDS';
export const SET_CURRENT_BOARD_LISTS='SET_CURRENT_BOARD_LISTS';

export const EDIT_COLUMN_TITLE='EDIT_COLUMN_TITLE';
export const EDIT_CARD_TITLE='EDIT_CARD_TITLE';
export const ADD_CARD='ADD_CARD';
export const ADD_COLUMN='ADD_COLUMN';


export const ADD_BOARD ='ADD_BOARD';


